/*
 * Include file for user programs using the Mathomatic symbolic math library API.
 */

#ifndef MATHOMATIC_LIB_H
#define MATHOMATIC_LIB_H

#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef EXPORT	/* already defined (as dllexport) by includes.h when compiling the library itself */
# if SHARED_LIB && defined _WIN32
#  define EXPORT __declspec(dllimport)
# else
#  define EXPORT
# endif
#endif

EXPORT int matho_init(void);				/* one-time Mathomatic initialization */
EXPORT FILE *matho_outfile (FILE *fp);			/* set output, return previous */
EXPORT int matho_process(char *input, char **outputp);	/* Mathomatic command or expression input */
EXPORT int matho_parse(char *input, char **outputp);	/* Mathomatic expression or equation input */
EXPORT void matho_clear(void);				/* Restart Mathomatic quickly and cleanly, replaces clear_all(). */

EXPORT void free_mem(void);	/* Free all allocated memory before quitting Mathomatic, if operating system doesn't when done. */
				/* Mathomatic becomes unusable after free_mem(), until matho_init() is called again. */
				/* Only Symbian OS is known to need a call to free_mem() before quitting. */

EXPORT int load_rc(int return_true_if_no_file, FILE *ofp);	/* Load Mathomatic startup set options from ~/.mathomaticrc, should allow "set save" to work. */

#if !SHARED_LIB

extern int cur_equation;	/* current equation space number (origin 0) */

extern int result_en;		/* Equation number of the API's returned result, */
				/* if the result is also stored in an equation space, */
				/* otherwise -1 for no equation number associated with result. */
				/* Set by the last call to matho_parse() or matho_process(). */
				/* Useful if you want to know where the result string is from, */
				/* to act on it with further commands. */

extern const char *warning_str;	/* optional warning message generated by the last command */

#else

EXPORT int matho_current_eqn(void);
EXPORT int matho_result_eqn(void);
EXPORT const char *matho_warning(void);

#endif

#ifdef __cplusplus
}
#endif

#endif/*ndef MATHOMATIC_LIB_H*/
